_BASE_: "Misc/scratch_mask_rcnn_R_50_FPN_3x_gn.yaml" #"../COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
DATALOADER:
  NUM_WORKERS: 2

INPUT:
  MIN_SIZE_TRAIN: (1365,)
  MIN_SIZE_TEST: 1365
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  FORMAT: "BGR"

MODEL:
  BACKBONE:
    FREEZE_AT: 0
    SFT_AT: 0 #must be <= 5 (5 resnet blocks, where 1 is the stem)
  ROI_HEADS:
    FREEZE: False # if True freeze ROI heads
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.9
    NMS_THRESH_TEST: 0.5
  FPN:
    FREEZE: False  # if True, applies SFT to same res block as SFT-ed backbone. Set False if only stem is SFT-ed
    JOINT_SFT: False
  RPN:
    FREEZE: False # If True, freeze RPN heads

  PIXEL_MEAN:  [103.530, 116.280, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]

#SOLVER OPTIONS
SOLVER:
  MAX_ITER: 2750
  IMS_PER_BATCH: 2
  WARMUP_ITERS: 165
  BASE_LR: 0.00125
  STEPS: [1925, 2475] # 5% warmup, 5-70 % + 70-90% 0.0001,

TEST:
  EVAL_PERIOD: 55
  AUG:
    MIN_SIZES: (1365)
    MAX_SIZE: 2048
