_BASE_: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
cfg.DATALOADER.NUM_WORKERS = 2

cfg.INPUT.MIN_SIZE_TRAIN = (1365)
cfg.INPUT.MIN_SIZE_TEST = (1365)
cfg.INPUT.MAX_SIZE_TRAIN = 2048
cfg.INPUT.MAX_SIZE_TEST = 2048
cfg.INPUT.MIN_SIZE_TRAIN_SAMPLING = "choice"
cfg.INPUT.FORMAT = "BGR"

cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(custom_cfg) #they are "" in the config
cfg.MODEL.BACKBONE.FREEZE_AT = 0
cfg.MODEL.BACKBONE.SFT_AT = 0 #must be <= 5 (5 resnet blocks, where 1 is the stem)
cfg.MODEL.ROI_HEADS.FREEZE = False # if True freeze ROI heads
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.9
cfg.MODEL.ROI_HEADS.NMS_THRESH_TEST = 0.5
cfg.MODEL.FPN.FREEZE = False  # if True, applies SFT to same res block as SFT-ed backbone. Set False if only stem is SFT-ed
cfg.MODEL.FPN.JOINT_SFT= False
cfg.MODEL.RPN.FREEZE = False # If True, freeze RPN heads

#SOLVER OPTIONS
cfg.SOLVER.MAX_ITER = 2750
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.WARMUP_ITERS = 165
cfg.SOLVER.BASE_LR = 0.00125
cfg.SOLVER.STEPS = [1925, 2475] # 5% warmup, 5-70 % + 70-90% 0.0001,
#cfg.SOLVER.MAX_ITER = 10000

cfg.TEST.EVAL_PERIOD = 39
cfg.TEST.AUG.MIN_SIZES = (1365)
cfg.TEST.AUG.MAX_SIZE = 2048

#BGR IMAGENET
cfg.MODEL.PIXEL_MEAN =  [103.530, 116.280, 123.675]                              #BGR: [113.603, 123.196, 118.612]          RGB: [118.612, 123.196, 113.603]
cfg.MODEL.PIXEL_STD = [1.0, 1.0, 1.0]                                            #BGR: [0.30522742, 0.26201303, 0.25535114]    RGB: [0.25535114, 0.26201303, 0.30522742]

